#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

case $BRANCH_NAME in
  "main")
    echo "integration-API-ECS-Service"
    ;;

  "staging")
    echo "stage-API-ECS-Service"
    ;;

  "release")
    echo "production-API-ECS-Service"
    ;;

  *)
    >&2 echo "unknown branch name"
    exit 9
esac