#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

case $BRANCH_NAME in
  "main")
    echo "superset_integration"
    ;;

  "staging")
    echo "superset_staging"
    ;;

  "release")
    echo "superset_production"
    ;;

  *)
    >&2 echo "unknown branch name"
    exit 9
esac
