#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

case $BRANCH_NAME in
  "main")
    echo "integration-serverless-container-api"
    ;;

  "staging")
    echo "stage-serverless-container-api"
    ;;

  "release")
    echo "production-serverless-container-api"
    ;;

  *)
    >&2 echo "unknown branch name"
    exit 9
esac