#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

case $BRANCH_NAME in
  "main")
    echo "mortgagebroker_production_lender_portal_v14"
    ;;

  "staging")
    echo "mortgagebroker_production_lender_portal_v14"
    ;;

  "release")
    echo "mortgagebroker_production_lender_portal_v14"
    ;;

  *)
    >&2 echo "unknown branch name"
    exit 9
esac
