#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

case $BRANCH_NAME in
  "main")
    echo "mortgagebroker-integration-superset-fargate"
    ;;

  "staging")
    echo "mortgagebroker-stage-superset-fargate"
    ;;

  "release")
    echo "mortgagebroker-production-superset-fargate"
    ;;

  *)
    >&2 echo "unknown branch name"
    exit 9
esac